name: Process gallery images

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - 'images/original/**.[Pp][Nn][Gg]'
      - 'images/original/**.[Jj][Pp][Gg]'
      - 'images/original/**.[Jj][Pp][Ee][Gg]'

jobs:
  build-gallery:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ checkout full history so git diff works
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    # 2 ▸ python + Pillow
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: pip install pillow

    # 3 ▸ list newly-ADDED images (path may contain spaces / commas)
    - id: added
      name: Find added images
      shell: bash
      run: |
        set -euo pipefail
        LIST=$(git diff --diff-filter=A --name-only \
                "${{ github.event.before }}" "${{ github.sha }}" \
              | grep -Ei '^images/original/.*\.(png|jpe?g)$' || true)
        echo "Added files:"
        printf '%s\n' "$LIST"
        echo "added<<EOF"   >> "$GITHUB_OUTPUT"
        printf '%s\n' "$LIST" >> "$GITHUB_OUTPUT"
        echo "EOF"          >> "$GITHUB_OUTPUT"

    # 4 ▸ full commit message becomes the title
    - id: title
      name: Capture commit message as title
      shell: bash
      run: |
        TITLE="${{ github.event.head_commit.message }}"
        CLEAN=$(echo "$TITLE" | tr '\n' ' ' | sed 's/  */ /g')
        echo "title=$CLEAN" >> "$GITHUB_OUTPUT"

    # 5 ▸ run your script for each new image (paths with spaces handled)
    - name: Generate thumbnails & metadata
      if: steps.added.outputs.added != ''
      shell: bash
      run: |
        set -euo pipefail
        while IFS= read -r FILE; do
          [ -z "$FILE" ] && continue   # skip empty lines
          BASENAME=$(basename "$FILE")
          echo "▶ python generate_resized_images.py \"$BASENAME\" \"${{ steps.title.outputs.title }}\""
          python generate_resized_images.py "$BASENAME" "${{ steps.title.outputs.title }}"
        done <<< "${{ steps.added.outputs.added }}"

    # 6 ▸ commit thumbnails, metadata.json, README bump
    - name: Commit generated files
      if: steps.added.outputs.added != ''
      shell: bash
      run: |
        set -euo pipefail
        git config user.name  github-actions
        git config user.email actions@github.com
        git add images/thumbs metadata.json README.md || true
        if git diff --cached --quiet; then
          echo "Nothing to commit."
        else
          git commit -m "chore: auto-process new gallery images [skip ci]"
          git push
        fi